<?php 

//include "exemplo-01.php"; 
// INCLUDE, INCLUI O ARQUIVO FUNCIONANDO OU NÃO E PROCURA EM DIRETORIO ALTERNATIVO

require "inc/exemplo-01.php"; 
//REQUIRE, UTILIZA O ARQUIVO SOMENTE SE ELE EXISTIR OU SE ESTIVER FUNCIONANDO DEVIDAMENTE, COM O RESULTADO DE PARAR A APLICACAO CASO NAO ESTEJA, RECOMENDADO

//INC/ É O DIRETORIO NA MESMA SESSAO, ../VOLTA UM DIRETORIO E ACESSO O REQUERIDO

$resultado = somar(10, 25);

echo $resultado;

?>